# Generated by Django 5.2.1 on 2025-11-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaomanutencao',
            old_name='descricao',
            new_name='descricao_problema',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='validade_cnh',
        ),
        migrations.RemoveField(
            model_name='registroviagem',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='solicitacaomanutencao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='solicitacaomanutencao',
            name='motorista',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='quilometragem_atual',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='status',
        ),
        migrations.AddField(
            model_name='motorista',
            name='categoria',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quilometragem',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='data_saida',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='km_retorno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='km_saida',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
