# Generated by Django 5.2.8 on 2025-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0002_rename_descricao_solicitacaomanutencao_descricao_problema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='quilometragem',
            new_name='km_atual',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='solicitacaomanutencao',
            name='status',
        ),
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registroviagem',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaomanutencao',
            name='atendida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='data_saida',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitacaomanutencao',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=20),
        ),
    ]
