# Generated by Django 6.0 on 2025-12-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0003_rename_quilometragem_veiculo_km_atual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaomanutencao',
            old_name='atendida',
            new_name='concluida',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registroviagem',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10),
        ),
    ]
