# Generated by Django 6.0 on 2025-12-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frotas', '0004_rename_atendida_solicitacaomanutencao_concluida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
